In [1]:
import numpy as np

In [3]:
myarr = np.zeros(10)
print(myarr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
myarr = np.ones(10)
print(myarr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [33]:
myarr1 = np.ones(10) * 5
print(myarr1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [11]:
nwarr = np.arange(10,51)
print(nwarr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [13]:
nwarr = np.arange(10,51,2)
print(nwarr)
print(nwarr.dtype)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
int64


In [19]:
myarr = np.arange(9).reshape(3,3)
print(myarr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
myarri = np.eye(3)
print(myarri)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
print(np.random.randint(0,1))

0


In [29]:
print(np.random.normal(0,1,25))

[-0.68911131  0.03820894 -1.11336748  1.52443005  0.58461281  0.06076639
  0.54499402  0.20873822 -0.529384   -0.65046241  0.63260935  1.17584798
 -0.40851037  0.56352924  0.02218949  0.92969838  0.42338878  1.38666862
 -0.17011808 -0.43357487 -2.10429158  0.85480702 -0.56865251  0.71507352
 -2.01403285]
